//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UserSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOut
    {
        public int ID { get; set; }
        public string UserEmail { get; set; }

        [Required]
        public string ShippingAddress { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        public string Country { get; set; }

        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime DateOrdered { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public System.DateTime ExpiredDate { get; set; }

        [Required]
        [RegularExpression(@"^[0-9]+$")]
        public int CVV { get; set; }

        [Required]
        public string CardNum { get; set; }
    }
}
